// Code generated by protoc-gen-go. DO NOT EDIT.
// source: well_known_types/well_known_types.proto

package well_known_types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import api "google.golang.org/genproto/protobuf/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GripmockClient is the client API for Gripmock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GripmockClient interface {
	ApiInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*api.Api, error)
}

type gripmockClient struct {
	cc *grpc.ClientConn
}

func NewGripmockClient(cc *grpc.ClientConn) GripmockClient {
	return &gripmockClient{cc}
}

func (c *gripmockClient) ApiInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*api.Api, error) {
	out := new(api.Api)
	err := c.cc.Invoke(ctx, "/well_known_types.Gripmock/ApiInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GripmockServer is the server API for Gripmock service.
type GripmockServer interface {
	ApiInfo(context.Context, *empty.Empty) (*api.Api, error)
}

func RegisterGripmockServer(s *grpc.Server, srv GripmockServer) {
	s.RegisterService(&_Gripmock_serviceDesc, srv)
}

func _Gripmock_ApiInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GripmockServer).ApiInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/well_known_types.Gripmock/ApiInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GripmockServer).ApiInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gripmock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "well_known_types.Gripmock",
	HandlerType: (*GripmockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApiInfo",
			Handler:    _Gripmock_ApiInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "well_known_types/well_known_types.proto",
}

func init() {
	proto.RegisterFile("well_known_types/well_known_types.proto", fileDescriptor_well_known_types_79f0e9b76c3d9f98)
}

var fileDescriptor_well_known_types_79f0e9b76c3d9f98 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0x4f, 0xcd, 0xc9,
	0x89, 0xcf, 0xce, 0xcb, 0x2f, 0xcf, 0x8b, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x47, 0x17, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x40, 0x17, 0x97, 0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf,
	0x49, 0xd5, 0x07, 0xcb, 0x27, 0x95, 0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94, 0x54, 0x42, 0x94, 0x4b,
	0x49, 0xa2, 0x4b, 0x26, 0x16, 0x64, 0x42, 0xa4, 0x8c, 0x9c, 0xb9, 0x38, 0xdc, 0x8b, 0x32, 0x0b,
	0x72, 0xf3, 0x93, 0xb3, 0x85, 0xcc, 0xb9, 0xd8, 0x1d, 0x0b, 0x32, 0x3d, 0xf3, 0xd2, 0xf2, 0x85,
	0xc4, 0xf4, 0x20, 0x5a, 0xf4, 0x60, 0x5a, 0xf4, 0x5c, 0x41, 0xe6, 0x49, 0x89, 0x60, 0x88, 0x3b,
	0x16, 0x64, 0x26, 0xb1, 0x81, 0x79, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x55, 0xb9,
	0x1e, 0xc0, 0x00, 0x00, 0x00,
}
