// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protogen/example/advanced/advanced.proto

package advanced

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protogen_example_advanced_advanced_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protogen_example_advanced_advanced_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protogen_example_advanced_advanced_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ReturnCode    int32                  `protobuf:"varint,2,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_protogen_example_advanced_advanced_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_protogen_example_advanced_advanced_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_protogen_example_advanced_advanced_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Reply) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

var File_protogen_example_advanced_advanced_proto protoreflect.FileDescriptor

const file_protogen_example_advanced_advanced_proto_rawDesc = "" +
	"\n" +
	"(protogen/example/advanced/advanced.proto\x12\badvanced\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"B\n" +
	"\x05Reply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vreturn_code\x18\x02 \x01(\x05R\n" +
	"returnCode2:\n" +
	"\bGripmock\x12.\n" +
	"\bSayHello\x12\x11.advanced.Request\x1a\x0f.advanced.ReplyB0Z.github.com/tokopedia/gripmock/example/advancedb\x06proto3"

var (
	file_protogen_example_advanced_advanced_proto_rawDescOnce sync.Once
	file_protogen_example_advanced_advanced_proto_rawDescData []byte
)

func file_protogen_example_advanced_advanced_proto_rawDescGZIP() []byte {
	file_protogen_example_advanced_advanced_proto_rawDescOnce.Do(func() {
		file_protogen_example_advanced_advanced_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protogen_example_advanced_advanced_proto_rawDesc), len(file_protogen_example_advanced_advanced_proto_rawDesc)))
	})
	return file_protogen_example_advanced_advanced_proto_rawDescData
}

var file_protogen_example_advanced_advanced_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protogen_example_advanced_advanced_proto_goTypes = []any{
	(*Request)(nil), // 0: advanced.Request
	(*Reply)(nil),   // 1: advanced.Reply
}
var file_protogen_example_advanced_advanced_proto_depIdxs = []int32{
	0, // 0: advanced.Gripmock.SayHello:input_type -> advanced.Request
	1, // 1: advanced.Gripmock.SayHello:output_type -> advanced.Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protogen_example_advanced_advanced_proto_init() }
func file_protogen_example_advanced_advanced_proto_init() {
	if File_protogen_example_advanced_advanced_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protogen_example_advanced_advanced_proto_rawDesc), len(file_protogen_example_advanced_advanced_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protogen_example_advanced_advanced_proto_goTypes,
		DependencyIndexes: file_protogen_example_advanced_advanced_proto_depIdxs,
		MessageInfos:      file_protogen_example_advanced_advanced_proto_msgTypes,
	}.Build()
	File_protogen_example_advanced_advanced_proto = out.File
	file_protogen_example_advanced_advanced_proto_goTypes = nil
	file_protogen_example_advanced_advanced_proto_depIdxs = nil
}
