// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: wkt.proto

package wkt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	apipb "google.golang.org/protobuf/types/known/apipb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_wkt_proto protoreflect.FileDescriptor

const file_wkt_proto_rawDesc = "" +
	"\n" +
	"\twkt.proto\x12\x10well_known_types\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/api.proto2C\n" +
	"\bGripmock\x127\n" +
	"\aApiInfo\x12\x16.google.protobuf.Empty\x1a\x14.google.protobuf.ApiB<Z:github.com/tokopedia/gripmock/example/well_known_types;wktb\x06proto3"

var file_wkt_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
	(*apipb.Api)(nil),     // 1: google.protobuf.Api
}
var file_wkt_proto_depIdxs = []int32{
	0, // 0: well_known_types.Gripmock.ApiInfo:input_type -> google.protobuf.Empty
	1, // 1: well_known_types.Gripmock.ApiInfo:output_type -> google.protobuf.Api
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wkt_proto_init() }
func file_wkt_proto_init() {
	if File_wkt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wkt_proto_rawDesc), len(file_wkt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wkt_proto_goTypes,
		DependencyIndexes: file_wkt_proto_depIdxs,
	}.Build()
	File_wkt_proto = out.File
	file_wkt_proto_goTypes = nil
	file_wkt_proto_depIdxs = nil
}
