// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: bar/bar.proto

package multi_package

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_bar_bar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_bar_bar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_bar_bar_proto_rawDescGZIP(), []int{0}
}

func (x *Bar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_bar_bar_proto protoreflect.FileDescriptor

const file_bar_bar_proto_rawDesc = "" +
	"\n" +
	"\rbar/bar.proto\x12\x03bar\"\x19\n" +
	"\x03Bar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameBPZNgithub.com/tokopedia/gripmock/protogen/example/multi-package/bar;multi_packageb\x06proto3"

var (
	file_bar_bar_proto_rawDescOnce sync.Once
	file_bar_bar_proto_rawDescData []byte
)

func file_bar_bar_proto_rawDescGZIP() []byte {
	file_bar_bar_proto_rawDescOnce.Do(func() {
		file_bar_bar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bar_bar_proto_rawDesc), len(file_bar_bar_proto_rawDesc)))
	})
	return file_bar_bar_proto_rawDescData
}

var file_bar_bar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bar_bar_proto_goTypes = []any{
	(*Bar)(nil), // 0: bar.Bar
}
var file_bar_bar_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bar_bar_proto_init() }
func file_bar_bar_proto_init() {
	if File_bar_bar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bar_bar_proto_rawDesc), len(file_bar_bar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bar_bar_proto_goTypes,
		DependencyIndexes: file_bar_bar_proto_depIdxs,
		MessageInfos:      file_bar_bar_proto_msgTypes,
	}.Build()
	File_bar_bar_proto = out.File
	file_bar_bar_proto_goTypes = nil
	file_bar_bar_proto_depIdxs = nil
}
