// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file2.proto

package multifiles

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Request2 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request2) Reset()         { *m = Request2{} }
func (m *Request2) String() string { return proto.CompactTextString(m) }
func (*Request2) ProtoMessage()    {}
func (*Request2) Descriptor() ([]byte, []int) {
	return fileDescriptor_file2_6a46b4869ea0a05f, []int{0}
}
func (m *Request2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request2.Unmarshal(m, b)
}
func (m *Request2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request2.Marshal(b, m, deterministic)
}
func (dst *Request2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request2.Merge(dst, src)
}
func (m *Request2) XXX_Size() int {
	return xxx_messageInfo_Request2.Size(m)
}
func (m *Request2) XXX_DiscardUnknown() {
	xxx_messageInfo_Request2.DiscardUnknown(m)
}

var xxx_messageInfo_Request2 proto.InternalMessageInfo

func (m *Request2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type Reply2 struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ReturnCode           int32    `protobuf:"varint,2,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply2) Reset()         { *m = Reply2{} }
func (m *Reply2) String() string { return proto.CompactTextString(m) }
func (*Reply2) ProtoMessage()    {}
func (*Reply2) Descriptor() ([]byte, []int) {
	return fileDescriptor_file2_6a46b4869ea0a05f, []int{1}
}
func (m *Reply2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply2.Unmarshal(m, b)
}
func (m *Reply2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply2.Marshal(b, m, deterministic)
}
func (dst *Reply2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply2.Merge(dst, src)
}
func (m *Reply2) XXX_Size() int {
	return xxx_messageInfo_Reply2.Size(m)
}
func (m *Reply2) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply2.DiscardUnknown(m)
}

var xxx_messageInfo_Reply2 proto.InternalMessageInfo

func (m *Reply2) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Reply2) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func init() {
	proto.RegisterType((*Request2)(nil), "multifiles.Request2")
	proto.RegisterType((*Reply2)(nil), "multifiles.Reply2")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Gripmock2Client is the client API for Gripmock2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Gripmock2Client interface {
	// simple unary method
	SayHello(ctx context.Context, in *Request2, opts ...grpc.CallOption) (*Reply2, error)
}

type gripmock2Client struct {
	cc *grpc.ClientConn
}

func NewGripmock2Client(cc *grpc.ClientConn) Gripmock2Client {
	return &gripmock2Client{cc}
}

func (c *gripmock2Client) SayHello(ctx context.Context, in *Request2, opts ...grpc.CallOption) (*Reply2, error) {
	out := new(Reply2)
	err := c.cc.Invoke(ctx, "/multifiles.Gripmock2/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Gripmock2Server is the server API for Gripmock2 service.
type Gripmock2Server interface {
	// simple unary method
	SayHello(context.Context, *Request2) (*Reply2, error)
}

func RegisterGripmock2Server(s *grpc.Server, srv Gripmock2Server) {
	s.RegisterService(&_Gripmock2_serviceDesc, srv)
}

func _Gripmock2_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Gripmock2Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multifiles.Gripmock2/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Gripmock2Server).SayHello(ctx, req.(*Request2))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gripmock2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "multifiles.Gripmock2",
	HandlerType: (*Gripmock2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Gripmock2_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file2.proto",
}

func init() { proto.RegisterFile("file2.proto", fileDescriptor_file2_6a46b4869ea0a05f) }

var fileDescriptor_file2_6a46b4869ea0a05f = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xb1, 0x0e, 0x82, 0x40,
	0x10, 0x44, 0x83, 0x51, 0x84, 0xa5, 0xdb, 0x58, 0x10, 0x0b, 0x25, 0x54, 0x54, 0x14, 0xa7, 0x3f,
	0x60, 0x28, 0xb4, 0x3e, 0x3f, 0xc0, 0x20, 0xac, 0x86, 0x78, 0xc7, 0xe2, 0xdd, 0x51, 0xf0, 0xf7,
	0x06, 0x0c, 0x31, 0x76, 0x33, 0x2f, 0x93, 0xcc, 0x83, 0xe8, 0xd1, 0x28, 0x12, 0x79, 0x67, 0xd8,
	0x31, 0x82, 0xee, 0x95, 0x6b, 0x46, 0x62, 0xd3, 0x1d, 0x04, 0x92, 0xde, 0x3d, 0x59, 0x27, 0x10,
	0x61, 0xd9, 0x96, 0x9a, 0x62, 0x2f, 0xf1, 0xb2, 0x50, 0x4e, 0x39, 0x2d, 0xc0, 0x97, 0xd4, 0xa9,
	0x41, 0x60, 0x0c, 0x6b, 0x4d, 0xd6, 0x96, 0xcf, 0x79, 0x30, 0x57, 0xdc, 0x43, 0x64, 0xc8, 0xf5,
	0xa6, 0xbd, 0x55, 0x5c, 0x53, 0xbc, 0x48, 0xbc, 0x6c, 0x25, 0xe1, 0x8b, 0x0a, 0xae, 0x49, 0x9c,
	0x20, 0x3c, 0x9b, 0xa6, 0xd3, 0x5c, 0xbd, 0x04, 0x1e, 0x21, 0xb8, 0x96, 0xc3, 0x85, 0x94, 0x62,
	0xdc, 0xe4, 0x3f, 0x95, 0x7c, 0xf6, 0xd8, 0xe2, 0x3f, 0x1d, 0xdf, 0xef, 0xfe, 0xa4, 0x7e, 0xf8,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x58, 0xdc, 0x5d, 0xb0, 0xc9, 0x00, 0x00, 0x00,
}
