// DO NOT EDIT. This file is autogenerated by GripMock
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"net"
	"net/http"

	"github.com/mitchellh/mapstructure"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
)

const (
	TCP_ADDRESS = ""
	HTTP_PORT   = ":"
)

type Greeter struct{}

func (s *Greeter) SayHello(ctx context.Context, in *HelloRequest) (*HelloReply, error) {
	out := &HelloReply{}
	err := findStub("Greeter", "SayHello", in, out)
	return out, err
}

func (s *Greeter) ServerStream(stream Greeter_ServerStreamServer) error {
	for {
		input, err := stream.Recv()
		if err == io.EOF {
			out := &HelloReply{}
			err := findStub("Greeter", "ServerStream", input, out)
			if err != nil {
				return err
			}
			return stream.SendAndClose(out)
		}
		if err != nil {
			return err
		}
	}
}

func (s *Greeter) ClientStream(in *HelloRequest, stream Greeter_ClientStreamServer) error {
	out := &HelloReply{}
	err := findStub("Greeter", "ClientStream", in, out)
	if err != nil {
		return err
	}

	return stream.Send(out)
}

func (s *Greeter) Bidirectional(stream Greeter_BidirectionalServer) error {
	for {
		in, err := stream.Recv()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}

		out := &HelloReply{}
		err = findStub("Greeter", "Bidirectional", in, out)
		if err != nil {
			return err
		}

		if err := stream.Send(out); err != nil {
			return err
		}
	}
}

func main() {
	lis, err := net.Listen("tcp", TCP_ADDRESS)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	s := grpc.NewServer()

	RegisterGreeterServer(s, &Greeter{})

	reflection.Register(s)
	fmt.Println("Serving gRPC on tcp://" + TCP_ADDRESS)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}

type payload struct {
	Service string      `json:"service"`
	Method  string      `json:"method"`
	Data    interface{} `json:"data"`
}

type response struct {
	Data  interface{} `json:"data"`
	Error string      `json:"error"`
}

func findStub(service, method string, in, out interface{}) error {
	url := fmt.Sprintf("http://localhost%s/find", HTTP_PORT)
	pyl := payload{
		Service: service,
		Method:  method,
		Data:    in,
	}
	byt, err := json.Marshal(pyl)
	if err != nil {
		return err
	}
	reader := bytes.NewReader(byt)
	resp, err := http.DefaultClient.Post(url, "application/json", reader)
	if err != nil {
		return fmt.Errorf("Error request to stub server %v", err)
	}

	if resp.StatusCode != http.StatusOK {
		body, _ := ioutil.ReadAll(resp.Body)
		return fmt.Errorf(string(body))
	}

	respRPC := new(response)
	err = json.NewDecoder(resp.Body).Decode(respRPC)
	if err != nil {
		return fmt.Errorf("decoding json response %v", err)
	}

	if respRPC.Error != "" {
		return fmt.Errorf(respRPC.Error)
	}

	return mapstructure.Decode(respRPC.Data, out)
}
