// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_7855ae276b57bab3, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_7855ae276b57bab3, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "main.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "main.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	ServerStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_ServerStreamClient, error)
	ClientStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_ClientStreamClient, error)
	Bidirectional(ctx context.Context, opts ...grpc.CallOption) (Greeter_BidirectionalClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/main.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) ServerStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_ServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/main.Greeter/serverStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServerStreamClient{stream}
	return x, nil
}

type Greeter_ServerStreamClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterServerStreamClient struct {
	grpc.ClientStream
}

func (x *greeterServerStreamClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterServerStreamClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) ClientStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_ClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[1], "/main.Greeter/clientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterClientStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_ClientStreamClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterClientStreamClient struct {
	grpc.ClientStream
}

func (x *greeterClientStreamClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) Bidirectional(ctx context.Context, opts ...grpc.CallOption) (Greeter_BidirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[2], "/main.Greeter/bidirectional", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterBidirectionalClient{stream}
	return x, nil
}

type Greeter_BidirectionalClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterBidirectionalClient struct {
	grpc.ClientStream
}

func (x *greeterBidirectionalClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterBidirectionalClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	ServerStream(Greeter_ServerStreamServer) error
	ClientStream(*HelloRequest, Greeter_ClientStreamServer) error
	Bidirectional(Greeter_BidirectionalServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).ServerStream(&greeterServerStreamServer{stream})
}

type Greeter_ServerStreamServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterServerStreamServer struct {
	grpc.ServerStream
}

func (x *greeterServerStreamServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterServerStreamServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).ClientStream(m, &greeterClientStreamServer{stream})
}

type Greeter_ClientStreamServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterClientStreamServer struct {
	grpc.ServerStream
}

func (x *greeterClientStreamServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_Bidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).Bidirectional(&greeterBidirectionalServer{stream})
}

type Greeter_BidirectionalServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterBidirectionalServer struct {
	grpc.ServerStream
}

func (x *greeterBidirectionalServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterBidirectionalServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "serverStream",
			Handler:       _Greeter_ServerStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "clientStream",
			Handler:       _Greeter_ClientStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "bidirectional",
			Handler:       _Greeter_Bidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_hello_7855ae276b57bab3) }

var fileDescriptor_hello_7855ae276b57bab3 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x3f, 0x4b, 0x04, 0x31,
	0x10, 0xc5, 0x09, 0x1c, 0x9e, 0x8e, 0x27, 0xca, 0x54, 0x87, 0x36, 0xb2, 0x85, 0x5c, 0x15, 0x82,
	0x82, 0x60, 0x7b, 0x8d, 0x96, 0xc7, 0x5d, 0x61, 0x9d, 0xdd, 0x1d, 0xd6, 0x40, 0xfe, 0x39, 0x89,
	0x7f, 0xf6, 0x0b, 0xfb, 0x39, 0x24, 0xc1, 0x05, 0xed, 0xd6, 0xee, 0xcd, 0xe3, 0xfd, 0xe6, 0xc1,
	0x83, 0xd3, 0x17, 0xb2, 0x36, 0xc8, 0xc8, 0x21, 0x07, 0x5c, 0x38, 0x6d, 0x7c, 0xd3, 0xc0, 0xea,
	0xa9, 0x98, 0x7b, 0x7a, 0x7d, 0xa3, 0x94, 0x11, 0x61, 0xe1, 0xb5, 0xa3, 0xb5, 0xb8, 0x16, 0x9b,
	0x93, 0x7d, 0xd5, 0xcd, 0x0d, 0xc0, 0x4f, 0x26, 0xda, 0x11, 0xd7, 0xb0, 0x74, 0x94, 0x92, 0x1e,
	0xa6, 0xd0, 0x74, 0xde, 0x7e, 0x09, 0x58, 0x3e, 0x32, 0x51, 0x26, 0x46, 0x05, 0xc7, 0x07, 0x3d,
	0x56, 0x0c, 0x51, 0x96, 0x2a, 0xf9, 0xbb, 0xe7, 0xf2, 0xe2, 0x8f, 0x57, 0xfe, 0xde, 0xc3, 0x2a,
	0x11, 0xbf, 0x13, 0x1f, 0x32, 0x93, 0x76, 0xf3, 0xa8, 0x8d, 0x28, 0x5c, 0x67, 0x0d, 0xf9, 0xfc,
	0x1f, 0x4e, 0x09, 0x7c, 0x80, 0xb3, 0xd6, 0xf4, 0x86, 0xa9, 0xcb, 0x26, 0x78, 0x6d, 0xe7, 0x16,
	0x2a, 0xb1, 0x55, 0x70, 0x65, 0x82, 0x1c, 0x38, 0x76, 0x92, 0x3e, 0xb5, 0x8b, 0x96, 0x92, 0xac,
	0xd3, 0x7e, 0x04, 0xb6, 0xfd, 0xf6, 0xbc, 0xc6, 0x9f, 0x8b, 0xde, 0x95, 0xa9, 0x77, 0xa2, 0x3d,
	0xaa, 0x9b, 0xdf, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xea, 0x81, 0xec, 0x7e, 0x82, 0x01, 0x00,
	0x00,
}
